### ISSUE TITLE
Refuses to work on server

### ISSUE THREAD

**Issue by lousassole** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#1]
Attempted to run this on a dedicated server (which was working before installing this mod). After installation and configuration (identical configs on client and host), nobody can connect to the server. Not sure what the issue is, as the only message received is that the client "failed to connect".

**Comment by Digitalroot** [comment]
Would you post your server log and client log.

**Comment by lousassole** [comment]
Turns out one of the dependencies was not installed properly initially, however no logs were generated indicating anything out of the ordinary on either side. Seems to be working fine now though. Sorry to bother you!

**Comment by Digitalroot** [comment]
Glad you figured it out
