### ISSUE TITLE
[Feature]: different size settings for the different types of dungeons

### ISSUE THREAD

**Issue by cawphee-black** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#16]
### Problem

Forrest crypts are more "open" in that there fewer barriers between areas and all the barriers are ones that the monsters can destroy. So a larger forest crypt is much harder relative to a larger swamp crypt because of all the monsters that can gather together from different areas.
I find it very hard to break a forest crypt because of how many skeletons come at me at once.

I guess this is kind of true for mountain caves too really. but I'm better equipped before I go into those very deeply.

### Solution

Please add different size settings based on the type of dungeon
So for example I can have small forest crypts but large swamp and mountain dungeons

### Alternatives

The only alternative is to remember to change the setting back to small in new games until I get at least bronze and then switch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
I'll have to check if at that point in the code the type is known.
