### ISSUE TITLE
[Bug]: Error on Startup and Shutdown

### ISSUE THREAD

**Issue by Kenkimaru** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#19]
### How are you playing the game?

Multiplayer - My Client Hosts Server

### What happened?

Ever since the last update I get 2 errors on startup and 1 Error while shutting down.

### To Reproduce

1. Start the Game
2. Look at the Bepinex Window
3. Close the Game
4. Look at the Bepinex Window

### Screenshots

![Error01](https://user-images.githubusercontent.com/120301852/206893595-9c6e6833-4309-489f-84a9-f3698c1983df.PNG)
![Error02](https://user-images.githubusercontent.com/120301852/206893596-1a12a2ea-94e8-453c-a079-1c9de5f542fc.PNG)

### Relevant log output

```shell
[All    :Digitalroot.Valheim.MaxDungeonRooms] Digitalroot.Valheim.MaxDungeonRooms.Main..ctor()
[All    :Digitalroot.Valheim.MaxDungeonRooms] Digitalroot.Valheim.MaxDungeonRooms.Main.Awake
[All    :Digitalroot.Valheim.MaxDungeonRooms] Digitalroot.Valheim.MaxDungeonRooms.Main.OnDestroy
```

### Log File

[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/files/10201732/LogOutput.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kenkimaru** [comment]
I just tested the new version with the Forest Crypts and they also throw errors now when they are getting generated.

[All    :Digitalroot.Valheim.MaxDungeonRooms] Digitalroot.Valheim.MaxDungeonRooms.PatchDungeonGeneratorPlaceRooms.Prefix
[All    :Digitalroot.Valheim.MaxDungeonRooms] [PatchDungeonGeneratorPlaceRooms] DG_ForestCrypt(Clone)

**Comment by Digitalroot** [comment]
Thanks. I left the trace on. Easy fix.

**Comment by Digitalroot** [comment]
You do have these errors in your log. 
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ABearCodes.Valheim.SimpleRecycling.UI.ContainerRecyclingButtonHolder.OnDestroy () (at <c6e465a4c1d9455c84ef58de8b238a7a>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ABearCodes.Valheim.SimpleRecycling.UI.StationRecyclingTabHolder.OnDestroy () (at <c6e465a4c1d9455c84ef58de8b238a7a>:0)

```

**Comment by Digitalroot** [comment]
Disabled the trace in 2.0.2

**Comment by Kenkimaru** [comment]
Thank you for the fast fix! 
And yeah I also noticed those other errors because of this and also saw they were already reported on the SimpleRecycling Fixed github so hopefully we'll see a fix for them in the future!
