### ISSUE TITLE
[Bug]: Dungeon loads, all destructible items become immune to dmg (like a static object but shows dmg numbers)

### ISSUE THREAD

**Issue by nowlflr** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#23]
### How are you playing the game?

Multiplayer - My Client Hosts Server

### What happened?

Dungeon loads, all destructible items become immune to dmg (like a static object but shows dmg numbers). Loaded this single mod and went to a dungeon. First one was fine but didn't have the minimum number of rooms set. Then the 2nd, 3rd, and 4th resulted in unable to destruct wood doors, vine doors, or shard glass (item holding the shard). Left dungeon, quit the game, and uninstalled the mod. Loaded back in and everything is good again.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nowlflr** [comment]
Disregard. I looked at the github noting an update 2 days ago but pulled mod from Thunderstore and didn't realize it said updated "2 months ago." So I'm sure this is probably because I was on the outdated one. I'll wait until it is uploaded over there and try again. Sorry for the confusion.

**Comment by Digitalroot** [comment]
If you continue to have an issue after the update. Try removing the mod. (your large dungeons should stay in your world.) and see if the issue goes away. If it does, let me know. I have a feeling there is another mod causing the issue you are experiencing.
