### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by thea1ien** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#24]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

World DB file becomes corrupt and unusable. The game will play until the world is shut down. I also tested this as single player with the same results. Loading from world backup, it keeps corrupting. It seems to do this when boating to Yagluth location (I suspect the issue triggers prior to arriving to Yagluth) It does it every time with the mod enabled, however with the mod disabled and sailing there I can shut the world down and load back in. On Dedicated server the error indicated a Negative value for a field that expects a positive value. Single player states "unable to read beyond the end of the stream". In case this helps.

Version of mod is 2.0.19. World Seed is QPL6a69ilx (Yagluth is in the far west of the world)
I have the Min Rooms set to 100, and Max set to 500 on all settings (Mod says it can go up to 1000)

### To Reproduce

Get on Longboat and sail to Yagluth. After shutting down the world, I find that the world file is now corrupt and unusable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Thank you for the details. I'm going to have to test this out.

**Comment by Digitalroot** [comment]
Jere — 08/05/2023 9:34 AM
Each ZDO can save up to 255 of specific data type. Because [IG] changed count to byte.
Currently save doesn't check for this and happily writes past the limit. (https://discord.com/channels/1094477020206993449/1094713280032948394/1137423481403879444)
