### ISSUE TITLE
Cannot D'ld from Nexus via Vortex [Bug]: 

### ISSUE THREAD

**Issue by Geralt-Rivian** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#25]
### How are you playing the game?

Single Player - No Server

### What happened?

Vortx cannot download "Max Dungeon rooms" mod for Valheim.  The error is ss below...

### To Reproduce

Open Vortex,  Get Mods, navigate to Max Dungeon Rooms...
Open "Files" tab
Click "ModManager Download"
Confirm "BepInEx" and "Jotunn", click "Download"
Vortex fails...

### Screenshots

![image](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/assets/143895843/fb8c1e5c-c1fa-4249-aa59-23bd865f4dee)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
I personally don't use vortex and the last time I looked into it it was bugged. So I'm not sure if there's anything I can do to resolve this issue.
