### ISSUE TITLE
Sealed Towers[Bug]: 

### ISSUE THREAD

**Issue by inimicalnibel** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#26]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

Sealed towers will sometimes duplicate themselves on top of one another, creating thousands of instances and mobs. Replicated on single player with mod enabled, but have not replicated it with mod disabled. First time raising an issue here, sorry if lacking info.

### To Reproduce

1. Start new seed.
2. Find Hildir.
3. Move to sealed tower.
4. With mod enabled, chance to spawn many clones of location. It does not happen to all Sealed Towers. 

### Screenshots

![image](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/assets/146622061/25d914c5-acd7-4cb1-8a5e-4925be5fe970)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VamPerL** [comment]
Had the same issue when getting into render distance. All the mobs spawned repeatedly onto another but at my location, so far away from the tower still. I disabled the mod but when approaching the tower the game starts lagging as hell. I have about 1 frame per 30 seconds. Tried to move away from the tower but it took too long and reloading the game doesn't seem to work anymore :D

**Comment by VamPerL** [comment]
Yes, that I also figured. yet would be nice to still have the mod running smoothly with the new dungeons/towers.

**Comment by Digitalroot** [comment]
Note to self: I need to find the name of the tower so the mod skips it.
