### ISSUE TITLE
[Bug]: Multiple caves spawned in each other

### ISSUE THREAD

**Issue by Shyzle** [Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms#28]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

Myself and one person entered a ice a cave. Other person entered first, then i entered. I have previous been in this cave before, time passed that allowed it to respawn everything in it. Other persons first time in the cave and we both have different layouts and we see each other walking through walls and on air.

### To Reproduce

1. Explore ice cave solo without anyone else and allow caves to respawn their items/monsters.
2. Enter cave with a friend, letting the friend enter the cave before you. Enter cave within 3 seconds of friend entering.
3. Watch friend walk into ceiling and or wall.
4. ???
5. Profit.

### Log File

[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/files/13656494/LogOutput.log) 
Friends log

[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/files/13656497/LogOutput.log) My client log

[LogOutput.log](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/files/13656501/LogOutput.log) Dedi server log

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Looking

**Comment by Digitalroot** [comment]
Edit your `BepInEx.cfg` file. Change the disk log level to Debug. 

![image](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/assets/3770289/cebfa80d-f454-4f3c-9549-5751e22189a5)

This should enable this debug logging

![image](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.MaxDungeonRooms/assets/3770289/64816fb2-bc29-4242-b629-3c20db349422)

Do this on all three systems. 

Go to the dungeon having the issue and duplicate the "issue". Re-post the logs. 

Q: I do not see any in the log files, do you have any other mods that change dungeons or reset them?
